### ISSUE TITLE
Slider does not stop 

### ISSUE THREAD

**Issue by stelehm** [dualcube/moodle-theme_roshnilite#15]
Hello,
and thanks for this very nice looking moodle theme.
I have an issue with the sliderbar on our frontpage that I seem unable to fix.
Even if I set the slidercount to 1, the frontpage does keep on "sliding" between this one slide.
Surely it would be more intuitive, if this slide-effect would only activate in cases where there are more than one slides.
Is there currently any way to keep the front-page from sliding, if there aren't any additional slides to display?

**Comment by parthajeet** [comment]
Hello,

Currently there is no such settings to stop the slider. We are hoping to add the same in our next update. If you wish you can stop the slider from bx slider js .

Path: your_moodle_folder/theme/roshnilite/js/engine.js

Change auto to false instead of true under the below given code snippet.
$('.top-slider').bxSlider({
});

Make sure to pugre all caches from the following site map after changing the code:

Home  ► Site administration  ► Development  ► Purge all caches

Regards,
Parthajeet~
